FROM ftp

# RUN apt update
# RUN apt install vsftpd -y
# service vsftpd stop

# mkdir -p /etc/vsftpd
# mv /etc/vsftpd.conf /etc/vsftpd/
# vim /etc/vsftpd/vsftpd.conf
# vim /etc/vsftpd.conf
# service vsftpd restart
# adduser misaki
# passwd misaki
# echo "misaki" | tee -a  /etc/vsftpd.chroot_list
# service vsftpd restart


# docker run -it -v /Users/mmounchi/Desktop/Docker:/home/vsftpd -p 20:20 -p 21:21 -p 47400-47470:47400-47470 -e FTP_USER=yourName -e FTP_PASS=yourPass -e PASV_ADDRESS=127.0.0.1 --name ftp --restart=always bogem/ftp
# docker run -it -p 20:20 -p 21:21 -p 40000-40009:40000-40009 -e FTP_USER=misaki -e FTP_PASS=misaki -e PASV_ADDRESS=127.0.0.1 --name ftp debian



# apt-get install -y procps net-tools vim
# netstat -npl
# CMD ["/usr/sbin/vsftpd","-obackground=NO"]

# user_local_user=NO
# userlist_enable=YES
# userlist_file=/etc/vsftpd.userlist 

# ----- TEST -----
# mkdir /home/misaki/ftp
# chown root:root /home/misaki/ftp
# chmod a-w /home/misaki/ftp

# mkdir /home/misaki/ftp/files
# chown misaki:misaki /home/misaki/ftp/files
# chmod 0700 /home/misaki/ftp/files



