version: '3'

services:
  mariadb:
    build: ./mariadb/
    image: mariadb
    ports:
      - 3306:3306
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Promisaki
      - MYSQL_PASSWORD=misaki
      - MYSQL_USER=misaki_user
      - MYSQL_DATABASE=misaki_db
    restart: on-failure
    networks:
      - lognet
  wordpress:
    build: ./wordpress/
    image: wordpress
    container_name: wordpress
    ports:
      #- 9000:9000      
      - 80:80
    volumes:
      -   wordpress_nginx:/var/www/html
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_PASSWORD=misaki
      - WORDPRESS_DB_NAME=misaki_db
      - WORDPRESS_DB_USER=misaki_user
    networks:
      - lognet
    restart: on-failure
  adminer:
    build: ./bonus/
    image: adminer
    container_name: adminer
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - lognet
  # nginx:
  #   image: nginx:alpine
  #   #volumes:
  #     # - nginx:/etc/nginx/conf.d
  #     # -   wordpress_nginx:/var/www/html
  #   ports:
  #     - 80:80
  #     - 443:443
  #   # links:
  #   #   - wordpress
volumes:
  mariadb_data:
  wordpress_nginx:

networks:
  lognet:
    name: mynetwork
    driver: bridge