version: '3'

services:
  mariadb:
    build: ./mariadb/
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: .env
    restart: always
    networks:
      - mynetwork

  wordpress:                         
    build: ./wordpress/
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress_nginx:/var/www/html
    depends_on:
      - mariadb
    env_file: .env
    networks:
      - mynetwork
    restart: always
    # tty: true
      
  nginx:
    build: ./nginx/
    image: nginx
    container_name: nginx
    volumes:
      - wordpress_nginx:/var/www/html
    ports:
      - 443:443
      - 0021:0021
    depends_on:
      - wordpress
    restart: always
    networks:
      - mynetwork
    
  # adminer:
  #   build: ./bonus/adminer/
  #   image: adminer
  #   container_name: adminer
  #   env_file: .env
  #   restart: always
  #   depends_on:
  #     - mariadb
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - mynetwork

  # ftp:
  #   build: ./bonus/ftp/
  #   image: ftp
  #   container_name: ftp
  #   env_file: .env
  #   restart: always
  #   # depends_on:
  #   #   - mariadb
  #   ports:
  #     - "21:21"
  #     - "47400-47470:47400-47470"
  #   volume:
  #     - ftp_data:
  #     - 
  #   networks:
  #     - mynetwork

volumes:
  mariadb_data:
  wordpress_nginx:
  # ftp_data:
      # device: /Users/mmounchi/Desktop/Data
      # name: wordpress_nginx

networks:
  mynetwork:
      # name: mynetwork
      driver: bridge