version: '3'

services:
  mariadb:
    build: ./mariadb/
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: .env
    restart: always
    networks:
      - mynetwork

  wordpress:                         
    build: ./wordpress/
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress_nginx:/var/www/html
    depends_on:
      - mariadb
    env_file: .env
    networks:
      - mynetwork
    restart: always
      
  nginx:
    build: ./nginx/
    image: nginx
    container_name: nginx
    volumes:
      - wordpress_nginx:/var/www/html
    ports:
      - 443:443
    depends_on:
      - wordpress
    restart: always
    networks:
      - mynetwork
    
  # adminer:
  #   build: ./bonus/adminer/
  #   image: adminer
  #   container_name: adminer
  #   env_file: .env
  #   restart: always
  #   depends_on:
  #     - mariadb
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - mynetwork

  # ftp:
  #   build:
  #     context: ./bonus/ftp/
  #     args: 
  #       - FTP_USER_NAME=$FTP_USER_NAME
  #       - FTP_USER_PASS=$FTP_USER_PASS
  #       - FTP_USER_HOME=$FTP_USER_HOME
  #   image: ftp
  #   container_name: ftp
  #   env_file: .env
  #   restart: always
  #   depends_on:
  #     - wordpress
  #   ports:
  #     - "21:21"
  #     - "40000-40009:40000-40009"
  #   volumes:
  #     - wordpress_nginx:/home/misaki/ftp
  #   networks:
  #     - mynetwork 

  redis:
    build: ./bonus/redis/
    image: redis
    container_name: redis
    env_file: .env
    restart: always
    depends_on:
      - wordpress
    ports:
      - 6379:6379
    networks:
      - mynetwork 
    # tty: true

volumes:
  wordpress_nginx:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mmounchi/Desktop/Docker/data/wordpress_nginx
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mmounchi/Desktop/Docker/data/mariadb_data

# volumes:
#   mariadb_data:
#     driver_opts:
#       type: none
#       o: bind
#       device: /home/misaki/Desktop/Docker/data/mariadb_data
#   wordpress_nginx:
#     driver_opts:
#       type: none
#       o: bind
#       device: /home/misaki/Desktop/Docker/data/wordpress_nginx

networks:
  mynetwork:
      # name: mynetwork
      driver: bridge