version: '3'

services:
  mariadb:
    build: ./mariadb/
    image: mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: .env
    restart: always
    networks:
      - mynetwork

  wordpress:                         
    build: ./wordpress/
    image: wordpress
    container_name: wordpress
    volumes:
      - wordpress_nginx:/var/www/html
    depends_on:
      - mariadb
    env_file: .env
    networks:
      - mynetwork
    restart: always
    # tty: true

  adminer:
    build: ./bonus/adminer/
    image: adminer
    container_name: adminer
    env_file: .env
    # environment:
    #   ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8080:8080
    networks:
      - mynetwork
      
  nginx:
    build: ./nginx/
    image: nginx
    container_name: nginx
    volumes:
      - wordpress_nginx:/var/www/html
    ports:
      - 443:443
    depends_on:
      - wordpress
    restart: always
    networks:
      - mynetwork

volumes:
  mariadb_data:
  # nginx:
  wordpress_nginx:
      # device: /Users/mmounchi/Desktop/Data
      # name: wordpress_nginx

networks:
  mynetwork:
      # name: mynetwork
      driver: bridge